"""empty message

Revision ID: 0289ce4fa360
Revises: 0728900639f6
Create Date: 2016-02-18 18:37:59.171596

"""

# revision identifiers, used by Alembic.
revision = '0289ce4fa360'
down_revision = '0728900639f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('company', sa.Column('postcode', sa.String(length=10), nullable=True))
    op.drop_column('company', 'address')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('company', 'postcode')
    op.drop_column('company', 'city')
    ### end Alembic commands ###
