"""empty message

Revision ID: 0728900639f6
Revises: d314a5596035
Create Date: 2016-02-18 15:42:36.835543

"""

# revision identifiers, used by Alembic.
revision = '0728900639f6'
down_revision = 'd314a5596035'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('logo', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'logo')
    ### end Alembic commands ###
