"""empty message

Revision ID: 0e6ee3b56926
Revises: None
Create Date: 2016-02-09 14:00:18.624958

"""

# revision identifiers, used by Alembic.
revision = '0e6ee3b56926'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    ### end Alembic commands ###
