"""empty message

Revision ID: 107743f414c2
Revises: 64502bd85d3e
Create Date: 2016-02-16 17:01:14.366252

"""

# revision identifiers, used by Alembic.
revision = '107743f414c2'
down_revision = '64502bd85d3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    ### end Alembic commands ###
