"""empty message

Revision ID: 415f6eedf7d4
Revises: aca2611ac8b1
Create Date: 2016-02-19 10:04:18.183734

"""

# revision identifiers, used by Alembic.
revision = '415f6eedf7d4'
down_revision = 'aca2611ac8b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'photo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('photo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    ### end Alembic commands ###
