"""empty message

Revision ID: 61d2ad8d7104
Revises: a8b72d938bd5
Create Date: 2016-02-19 11:13:11.460507

"""

# revision identifiers, used by Alembic.
revision = '61d2ad8d7104'
down_revision = 'a8b72d938bd5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('summary', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'summary')
    ### end Alembic commands ###
