"""empty message

Revision ID: 782022699ae9
Revises: c0312cb50f2e
Create Date: 2016-02-11 11:37:13.144773

"""

# revision identifiers, used by Alembic.
revision = '782022699ae9'
down_revision = 'c0312cb50f2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    ### end Alembic commands ###
