"""empty message

Revision ID: 93795a9c4453
Revises: 76b12d078e4d
Create Date: 2016-02-19 10:06:24.876460

"""

# revision identifiers, used by Alembic.
revision = '93795a9c4453'
down_revision = '76b12d078e4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'photo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('photo', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    ### end Alembic commands ###
