"""empty message

Revision ID: a8b72d938bd5
Revises: d0511ef50853
Create Date: 2016-02-19 11:12:50.938115

"""

# revision identifiers, used by Alembic.
revision = 'a8b72d938bd5'
down_revision = 'd0511ef50853'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'summary')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('summary', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    ### end Alembic commands ###
