"""empty message

Revision ID: ba3ee086cfff
Revises: f8ec1eb3db7a
Create Date: 2016-02-15 23:29:55.565457

"""

# revision identifiers, used by Alembic.
revision = 'ba3ee086cfff'
down_revision = 'f8ec1eb3db7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('location', sa.String(), nullable=True))
    op.add_column('job', sa.Column('perks', sa.String(), nullable=True))
    op.add_column('job', sa.Column('salary', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('summary', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'summary')
    op.drop_column('job', 'salary')
    op.drop_column('job', 'perks')
    op.drop_column('job', 'location')
    ### end Alembic commands ###
