"""empty message

Revision ID: c0312cb50f2e
Revises: 0e6ee3b56926
Create Date: 2016-02-11 11:21:59.577719

"""

# revision identifiers, used by Alembic.
revision = 'c0312cb50f2e'
down_revision = '0e6ee3b56926'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('companies')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='companies_pkey')
    )
    op.drop_table('company')
    ### end Alembic commands ###
