"""empty message

Revision ID: c5754503356f
Revises: 782022699ae9
Create Date: 2016-02-11 11:43:24.011375

"""

# revision identifiers, used by Alembic.
revision = 'c5754503356f'
down_revision = '782022699ae9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person', 'company', ['company_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'company_id')
    ### end Alembic commands ###
