"""empty message

Revision ID: d0511ef50853
Revises: 93795a9c4453
Create Date: 2016-02-19 10:06:41.739526

"""

# revision identifiers, used by Alembic.
revision = 'd0511ef50853'
down_revision = '93795a9c4453'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('photo', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'photo')
    ### end Alembic commands ###
