"""empty message

Revision ID: f8ec1eb3db7a
Revises: d641a7af58e4
Create Date: 2016-02-15 23:01:26.658967

"""

# revision identifiers, used by Alembic.
revision = 'f8ec1eb3db7a'
down_revision = 'd641a7af58e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('person', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.add_column('person', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('person', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('person', sa.Column('website', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'person', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'website')
    op.drop_column('person', 'summary')
    op.drop_column('person', 'location')
    op.drop_column('person', 'job_title')
    op.drop_column('person', 'email')
    ### end Alembic commands ###
